services:
  staycation:
    build: .
    ports:
      - "5000:5000"
      - "27017:27017"  # Expose MongoDB port if needed
    # environment:
    #   - FLASK_ENV=${FLASK_ENV:-development}
    # volumes:
    #   - ict381vol:/staycation/data/db
    env_file:
      - .env

volumes:
  ict381vol: